// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GGLYW_pYVbN_8n4YvKViV1bkbGDSLCk',
    appId: '1:206040821438:web:44612e028a451d0e63f8ef',
    messagingSenderId: '206040821438',
    projectId: 'myecomerceapp-27315',
    authDomain: 'myecomerceapp-27315.firebaseapp.com',
    storageBucket: 'myecomerceapp-27315.firebasestorage.app',
    measurementId: 'G-T4REWKJBC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1jduFCgunc3YCYKD1_9NnaGBZbgFt08',
    appId: '1:206040821438:android:a798254ba925982463f8ef',
    messagingSenderId: '206040821438',
    projectId: 'myecomerceapp-27315',
    storageBucket: 'myecomerceapp-27315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP-A_aZoRyIx0cJwsK7IVJorhqcYEMDXQ',
    appId: '1:206040821438:ios:c83231b86fca72cc63f8ef',
    messagingSenderId: '206040821438',
    projectId: 'myecomerceapp-27315',
    storageBucket: 'myecomerceapp-27315.firebasestorage.app',
    iosBundleId: 'com.example.myecomerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP-A_aZoRyIx0cJwsK7IVJorhqcYEMDXQ',
    appId: '1:206040821438:ios:c83231b86fca72cc63f8ef',
    messagingSenderId: '206040821438',
    projectId: 'myecomerceapp-27315',
    storageBucket: 'myecomerceapp-27315.firebasestorage.app',
    iosBundleId: 'com.example.myecomerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9GGLYW_pYVbN_8n4YvKViV1bkbGDSLCk',
    appId: '1:206040821438:web:5a83b64408d330ef63f8ef',
    messagingSenderId: '206040821438',
    projectId: 'myecomerceapp-27315',
    authDomain: 'myecomerceapp-27315.firebaseapp.com',
    storageBucket: 'myecomerceapp-27315.firebasestorage.app',
    measurementId: 'G-T586TQ7Q47',
  );
}
